name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    name: Build and Deploy Blazor WASM to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      checks: read
    env:
      PROJECT_NAME: BlazorWasmPortfolioGhAction
      DOTNET_VERSION: '8.0.x'
      OUTPUT_FOLDER: release
      BASE_HREF: '/BlazorWasmPortfolioGhAction/'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean output directory
        run: rm -rf ${{ env.OUTPUT_FOLDER }}

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install WebAssembly Workload
        run: dotnet workload install wasm-tools

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Cache build outputs
        uses: actions/cache@v4
        with:
          path: |
            bin
            obj
          key: build-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}

      - name: Restore NuGet packages
        run: dotnet restore ${{ env.PROJECT_NAME }}.csproj

      - name: Build .NET Core Project
        run: dotnet build ${{ env.PROJECT_NAME }}.csproj --configuration Release --nologo

      - name: Publish .NET Core Project
        run: dotnet publish ${{ env.PROJECT_NAME }}.csproj --configuration Release --output ${{ env.OUTPUT_FOLDER }} --nologo --no-restore

      - name: Change base-tag in index.html
        shell: bash
        run: sed -i.bak 's|<base href="/" />|<base href="${{ env.BASE_HREF }}" />|g' ${{ env.OUTPUT_FOLDER }}/wwwroot/index.html

      - name: Verify base href
        run: cat ${{ env.OUTPUT_FOLDER }}/wwwroot/index.html

      - name: Remove backup file
        run: rm ${{ env.OUTPUT_FOLDER }}/wwwroot/index.html.bak

      - name: Copy index.html to 404.html
        run: cp ${{ env.OUTPUT_FOLDER }}/wwwroot/index.html ${{ env.OUTPUT_FOLDER }}/wwwroot/404.html

      - name: Add .nojekyll file
        run: touch ${{ env.OUTPUT_FOLDER }}/wwwroot/.nojekyll

      - name: Validate wwwroot folder
        run: ls -R ${{ env.OUTPUT_FOLDER }}/wwwroot

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ${{ env.OUTPUT_FOLDER }}/wwwroot
          CLEAN: true

      - name: Health Check
        run: |
          npm install -g serve

          # Create a simulated GitHub Pages directory structure
          mkdir -p health-check${{ env.BASE_HREF }}
          cp -r ${{ env.OUTPUT_FOLDER }}/wwwroot/* health-check${{ env.BASE_HREF }}

          # Serve from the parent directory
          npx serve health-check -l 3000 &
          sleep 5

          # Verify accessibility at BASE_HREF
          curl --retry 5 --retry-delay 3 --fail http://localhost:3000${{ env.BASE_HREF }}

          # Verify service-worker.js is accessible
          curl --retry 5 --retry-delay 3 --fail http://localhost:3000${{ env.BASE_HREF }}service-worker.js

      - name: Verify Deployment
        run: |
          git clone https://github.com/khoiduc/BlazorWasmPortfolioGhAction.git --branch gh-pages gh-pages
          ls -R gh-pages

      - name: Upload release folder as artifact
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: release-folder
          path: ${{ env.OUTPUT_FOLDER }}